name: Deploy Laravel
on:
  push:
    branches: [ "main" ] # Setiap kali ada update di branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/sidara
            # Paksa ubah pemilik ke user SSH agar Git tidak protes
            sudo chown -R $USER:$USER /var/www/sidara
            
            # Tambahkan safe.directory agar Git percaya pada folder ini
            git config --global --add safe.directory /var/www/sidara
            
            # Lakukan pull
            git pull origin main
            
            # Build & Restart Docker
            docker compose build
            docker compose up -d
